name:                projecteulerdotnet
version:             0.1.0.0
license:             BSD3
maintainer:          "example@example.com"
copyright:           "2020 Author name here"


dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
      - criterion
      - primes


executables:
  projecteulerdotnet-exe:
    source-dirs: src
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    main: bench.hs
